spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

messaging:
  consumers:
    wallet-balance-changed:
      queue: notification.wallet.updated.queue

poorbet:
  security:
    issuer: ${AUTH_ISSUER_URI}
    jwk-set-uri: ${AUTH_JWKS_URI}