spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

messaging:
  wallet-exchange: wallet.events
  wallet-queue: notification.wallet.updated.queue
  wallet-routing-key: wallet.balance.updated.v1

poorbet:
  security:
    enabled: false