version: "3.3"

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  odds-service:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MODEL_PATH=/app/data/models/match_predictor.onnx
    volumes:
      - ./odds-service:/app
      - ./data/models:/app/data/models
      - ~/.m2:/root/.m2
    ports:
      - "8085:8080"
      - "5072:5072"

  simulation-service:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./simulation-service:/app
      - ~/.m2:/root/.m2
    ports:
      - "8084:8080"
      - "5073:5073"


  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile.dev
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_KEY_ID=${JWT_KEY_ID}
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
      - ./.mvn:/app/.mvn
    networks:
      - main_network
    ports:
      - "8089:8080"
      - "5079:5079"
#    command: ./mvnw -pl user-service -am spring-boot:run

  teams-service:
    build:
      context: ./teams-service
      dockerfile: Dockerfile.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://teams-db:5432/${POSTGRES_TEAMS_DB}
      - POSTGRES_USER=${POSTGRES_TEAMS_USER}
      - POSTGRES_PASSWORD=${POSTGRES_TEAMS_PASSWORD}
    volumes:
      - ./teams-service:/app
      - ~/.m2:/root/.m2
    ports:
      - "8082:8080"
      - "5071:5071"

  match-service:
    build:
      context: ./match-service
      dockerfile: Dockerfile.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://match-db:5432/${POSTGRES_MATCH_DB}
      - POSTGRES_USER=${POSTGRES_MATCH_USER}
      - POSTGRES_PASSWORD=${POSTGRES_MATCH_PASSWORD}
      - INSTANCE_ID=match-1
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./match-service:/app
      - ~/.m2:/root/.m2
    ports:
      - "8083:8080"
      - "5070:5070"

  coupon-service:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://coupon-db:5432/${POSTGRES_COUPON_DB}
      - POSTGRES_USER=${POSTGRES_COUPON_USER}
      - POSTGRES_PASSWORD=${POSTGRES_COUPON_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./coupon-service:/app
      - ~/.m2:/root/.m2
    ports:
      - "8086:8080"
      - "5076:5076"
