x-auth-config: &auth-config
  AUTH_ISSUER_URI: ${AUTH_ISSUER_URI}
  AUTH_JWKS_URI: ${AUTH_JWKS_URI}

services:

  frontend:
    networks:
      - main_network

  gateway:
    environment:
      <<: *auth-config
    depends_on:
      - user-service
      - user-db
    networks:
      - main_network

  odds-training:
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - AUTH_SERVICE_CLIENT_ID=odds-training
      - AUTH_SERVICE_CLIENT_SECRET=${AUTH_SERVICE_CLIENT_SECRET}
    depends_on:
      - user-service
      - simulation-service
    networks:
      - main_network

  python-trainer:
    build: ./odds-training/python-scripts
    volumes:
      - ./data:/app/data
    networks:
      - main_network

  odds-service:
    depends_on:
      - user-service
    volumes:
      - ./data/models:/app/data/models
    environment:
      <<: *auth-config
    networks:
      - main_network

  simulation-service:
    depends_on:
      - user-service
    environment:
      <<: *auth-config
    networks:
      - main_network

  user-service:
    depends_on:
      - user-db
    environment:
      <<: *auth-config
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    networks:
      - main_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  teams-service:
    environment:
      <<: *auth-config
    depends_on:
      - teams-db
      - redis
    networks:
      - main_network

  match-service:
    environment:
      <<: *auth-config
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - match-db
      - teams-db
      - rabbitmq
      - redis
      - user-service
    networks:
      - main_network

  coupon-service:
    environment:
      <<: *auth-config
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - coupon-db
      - rabbitmq
      - redis
    networks:
      - main_network

  wallet-service:
    environment:
      <<: *auth-config
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - wallet-db
      - rabbitmq
      - redis
    networks:
      - main_network

  notification-service:
    environment:
      <<: *auth-config
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    networks:
      - main_network


  redis:
    image: redis:7.4-alpine
    volumes:
      - redis_data:/data
    networks:
      - main_network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - main_network

  user-db:
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - main_network

  match-db:
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_MATCH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MATCH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_MATCH_DB}
    volumes:
      - match_data:/var/lib/postgresql/data
    networks:
      - main_network

  wallet-db:
    environment:
      POSTGRES_USER: ${POSTGRES_WALLET_USER}
      POSTGRES_PASSWORD: ${POSTGRES_WALLET_PASSWORD}
      POSTGRES_DB: ${POSTGRES_WALLET_DB}
    volumes:
      - wallet_data:/var/lib/postgresql/data
    networks:
      - main_network

  coupon-db:
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_COUPON_USER}
      POSTGRES_PASSWORD: ${POSTGRES_COUPON_PASSWORD}
      POSTGRES_DB: ${POSTGRES_COUPON_DB}
    volumes:
      - coupon_data:/var/lib/postgresql/data
    networks:
      - main_network

  teams-db:
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_TEAMS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEAMS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEAMS_DB}
    volumes:
      - teams_data:/var/lib/postgresql/data
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  frontend_node_modules:
  training_data:
  models_data:

  redis_data:
  rabbitmq_data:

  user_data:
  match_data:
  wallet_data:
  coupon_data:
  teams_data: