spring:
  application:
    name: authorization-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: INFO
    org.flywaydb: DEBUG

auth:
  server:
    issuer: ${AUTH_SERVER_ISSUER:http://authorization-service:9000}
    audience: ${AUTH_SERVER_AUDIENCE:poorbet-api}
  cors:
    allowed-origins:
      - http://localhost:4200
  token:
    access-token-ttl: 15m
    refresh-token-ttl: 7d
    reuse-refresh-token: false
  clients:
    frontend:
      id: ${FRONTEND_CLIENT_ID}
      redirect-uri: ${FRONTEND_CLIENT_REDIRECT_URI}
      scopes:
        - openid
        - profile
        - users:read
        - offline_access