spring:
  application:
    name: odds-service

poorbet:
  security:
    enabled: true
    issuer: ${AUTH_ISSUER_URI}
    internal-audience:
      - odds-service
    jwk-set-uri: ${AUTH_JWKS_URI}

logging:
  level:
    root: INFO
    com.poorbet: DEBUG
