server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: public-user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/register
          filters:
            - StripPrefix=0

        - id: protected-user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-API-KEY, ${API_KEY}

        - id: match-service
          uri: http://match-service:8080
          predicates:
            - Path=/api/match/**

        - id: team-service
          uri: http://teams-service:8080
          predicates:
            - Path=/api/teams/**

        - id: coupon-service
          uri: http://coupon-service:8080
          predicates:
            - Path=/api/coupons/**

        - id: authorization-server
          uri: http://authorization-server:8080
          predicates:
            - Path=/.well-known/**, /oauth2/**, /userinfo, /login, /error

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER:http://authorization-server:8080}
          jwk-set-uri: ${AUTH_SERVER_JWK_SET_URI:http://authorization-server:8080/oauth2/jwks}
