server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: public-user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/login, /api/users/register
#          filters:
#            - StripPrefix=0

        - id: protected-user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**
#          filters:
#            - StripPrefix=0
#            - JwtAuthFilter

        - id: match-service
          uri: http://match-service:8080
          predicates:
            - Path=/api/match/**, /api/match-pool/**
          filters:
            - JwtAuthFilter

        - id: team-service
          uri: http://teams-service:8080
          predicates:
            - Path=/api/teams/**
          filters:
            - JwtAuthFilter


        - id: coupon-service
          uri: http://coupon-service:8086
          predicates:
            - Path=/api/coupons/**
          filters:
            - JwtAuthFilter

jwt:
  issuer: ${JWT_ISSUER:poorbet-auth-service}
  jwk-set-uri: ${AUTH_JWKS_URI:http://user-service:8080/.well-known/jwks.json}
