server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**

        - id: match-service
          uri: http://match-service:8080
          predicates:
            - Path=/api/match/**, /api/match-pool/**

        - id: team-service
          uri: http://teams-service:8080
          predicates:
            - Path=/api/teams/**

        - id: coupon-service
          uri: http://coupon-service:8080
          predicates:
            - Path=/api/coupons/**

        - id: wallet-service
          uri: http://wallet-service:8080
          predicates:
            - Path=/api/wallet/**

        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=/api/notifications/**

poorbet:
  security:
    enabled: false
    jwk-set-uri: ${AUTH_JWKS_URI}
    issuer: ${AUTH_ISSUER_URI}
    unprotected-paths:
      - /api/users/login
      - /api/users/register
      - /api/match-pool/**
      - /api/teams/public/**
      - /api/notifications/**
