FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY . .

EXPOSE 8085
EXPOSE 5072

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5072"]
