FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

EXPOSE 8080 5079

CMD ["mvn","-pl","user-service","-am","spring-boot:run","-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5079"]