FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

RUN apk add --no-cache bash

EXPOSE 8080 5070

CMD ["sh", "-c", "if [ -d /poorbet-commons ]; then /app/mvnw -f /poorbet-commons/pom.xml -DskipTests install; fi && ./mvnw -DskipTests clean spring-boot:run -Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5070"]
