name: Run microservices tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        service: [
          coupon-service,
          match-service,
          odds-service,
          odds-training,
          simulation-service,
          teams-service
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Run tests for ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: mvn clean test